{{- $fullName := include "memos.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "memos.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "memos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/settings: {{ include (print $.Template.BasePath "/settings.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "memos.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "memos.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: memos-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existPersistClaim | default ($fullName) }}
        {{- else }}
          emptyDir: { }
        {{- end }}
        {{- range $key, $section := .Values.settings }}
        {{- $hasConfig := and (hasKey $section "config") (not (empty $section.config)) }}
        {{- $hasSecret := and (hasKey $section "existingSecret") (not (empty $section.existingSecret)) }}
        {{- if or $hasConfig $hasSecret }}
        - name: setting-{{ $key }}
        {{- if $section.config }}
          configMap:
            name: {{ $fullName -}}-{{- $key }}
        {{- else if $section.existingSecret }}
          secret:
            secretName: {{ $section.existingSecret }}
        {{- end }}
            items:
              - key: setting
                path: setting
        {{- end }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repo}}/{{ .Values.image.imageName }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5230
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: memos-data
              mountPath: /var/opt/memos
            {{- range $key, $section := .Values.settings }}
            {{- $hasConfig := and (hasKey $section "config") (not (empty $section.config)) }}
            {{- $hasSecret := and (hasKey $section "existingSecret") (not (empty $section.existingSecret)) }}
            {{- if or $hasConfig $hasSecret }}
            {{- $fn := "" -}}
            {{- if hasPrefix "idp-" $key -}}
              {{- $fn = printf "memos-%s.json" $key -}}
            {{- else -}}
              {{- $fn = printf "memos-instance-setting-%s.json" $key -}}
            {{- end }}
            - name: setting-{{ $key }}
              mountPath: /etc/secrets/{{- $fn }}
              subPath: setting
              readOnly: true
            {{- end }}
            {{- end }}
          # avoid * cannot parse 'Port' as int: strconv.ParseInt: parsing "tcp://10.233.40.219:5230": invalid syntax
          env:
            - name: MEMOS_PORT
              value: "{{ .Values.service.port }}"
            - name: MEMOS_LOG_LEVEL
              value: {{ .Values.instance.logLevel | quote }}
            - name: MEMOS_DRIVER
              value: {{ .Values.database.driver | quote }}
            {{- if .Values.database.existingSecret }}
            - name: MEMOS_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.existingSecret.name }}
                  key: {{ .Values.database.existingSecret.key }}
            {{- else if .Values.database.connectionString }}
            - name: MEMOS_DSN
              value: {{ .Values.database.connectionString | quote }}
            {{- end }}
            {{- if .Values.instance.url }}
            - name: MEMOS_INSTANCE_URL
              value: {{ .Values.instance.url }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end}}

