{{- if eq .Values.database.driver "postgres" }}
  {{- if and (not .Values.database.postgres.dsn) (not .Values.database.postgres.existingSecret) }}
    {{- fail "database.postgres.dsn or database.postgres.existingSecret must be set" }}
  {{- end }}
{{- else if eq .Values.database.driver "mysql" }}
  {{- if and (not .Values.database.mysql.dsn) (not .Values.database.mysql.existingSecret) }}
    {{- fail "database.mysql.dsn or database.mysql.existingSecret must be set" }}
  {{- end }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "memos.fullname" . }}
  labels:
    {{- include "memos.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}

  selector:
    matchLabels:
      {{- include "memos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "memos.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "memos.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: memos-data
          {{- if and (eq .Values.database.driver "sqlite") .Values.database.sqlite.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.database.sqlite.persistence.existingClaim | default (include "memos.fullname" .) }}
          {{- else }}
          emptyDir: { }
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repo}}/{{ .Values.image.imageName }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5230
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: memos-data
              mountPath: /var/opt/memos
          # avoid * cannot parse 'Port' as int: strconv.ParseInt: parsing "tcp://10.233.40.219:5230": invalid syntax
          env:
            - name: MEMOS_PORT
              value: "{{ .Values.service.port }}"
            - name: MEMOS_DRIVER
              value: {{ .Values.database.driver }}
            {{- if eq .Values.database.driver "postgres" }}
            {{- if .Values.database.postgres.dsn }}
            - name: MEMOS_DSN
              value: {{ .Values.database.postgres.dsn | quote }}
            {{- else if .Values.database.postgres.existingSecret }}
            - name: MEMOS_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.postgres.existingSecret }}
                  key: {{ .Values.database.postgres.existingSecretKey | default "database-dsn" }}
            {{- end }}
            {{- end }}
            {{- if eq .Values.database.driver "mysql" }}
            {{- if .Values.database.mysql.dsn }}
            - name: MEMOS_DSN
              value: {{ .Values.database.mysql.dsn | quote }}
            {{- else if .Values.database.mysql.existingSecret }}
            - name: MEMOS_DSN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.database.mysql.existingSecret}}
                  key: {{ .Values.database.mysql.existingSecretKey | default "database-dsn" }}
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end}}

