{{- if and (eq .Values.database.driver "sqlite") .Values.database.sqlite.persistence.enabled (eq .Values.database.sqlite.persistence.existingClaim "") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "memos.fullname" . }}
  labels:
    {{- include "memos.labels" . | nindent 4 }}
spec:
  {{- with .Values.database.sqlite.persistence.storageClass }}
  storageClassName: {{ . }}
  {{- end}}
  accessModes:
    - {{ .Values.database.sqlite.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.database.sqlite.persistence.size | quote }}
{{- end -}}